### ISSUE TITLE
Getting Error while Generating Boilerplate for Table

### ISSUE THREAD

**Issue by raahulrathore** [XPRNetwork/ts-smart-contracts#11]
Tried creating table using `proton generate:table tableName --class=ClassName`
It keeps on saying **The contract file is not found. May be you forgot to create the contract first?**

Steps Done :

- Generate a contract using `proton generate:contract contractname`
- navigate to folder having contract
- use generate command to generate table boilerplate

![image](https://user-images.githubusercontent.com/30141344/224232307-3cc36dc9-af42-474d-948e-efc22be23a44.png)

If i do `ls` to check files, it do show me contract present in the directory
![image](https://user-images.githubusercontent.com/30141344/224233011-38865000-839f-49fb-8bb8-3c7ce339e799.png)

**Comment by andreyjamer** [comment]
Seems like the contract detection does not work properly in Windows. 
Try this command as a workaround for now:
```
proton generate:table kvs --class=AccountKV --contract=kv
```

**Comment by raahulrathore** [comment]
yes the issue seems to be OS specific, as it works fine in my other system having Linux.
thanks for the workaround

**Comment by andreyjamer** [comment]
The fix for Windows is almost ready. Will be released soon

**Comment by raahulrathore** [comment]
Awesome!! 👨‍💻🔥
